{"content": {"suites": {"0": {"status": {"total_pass": 1, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 3, "total_error": 0}, "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_database_connection", "rerun": "0"}, "1": {"status": "FAIL", "message": "   psycopg2.errors.UndefinedTable: relation \"users\" does not exist\n   LINE 1: INSERT INTO users (id, name) VALUES (1, 'John')\n                       ^\n", "test_name": "test_data_insertion", "rerun": "0"}, "2": {"status": "FAIL", "message": "   psycopg2.errors.UndefinedTable: relation \"users\" does not exist\n   LINE 1: UPDATE users SET name='Jane' WHERE id=1\n                  ^\n", "test_name": "test_update_data", "rerun": "0"}, "3": {"status": "FAIL", "message": "   psycopg2.errors.UndefinedTable: relation \"users\" does not exist\n   LINE 1: DELETE FROM users WHERE id=1\n                       ^\n", "test_name": "test_delete_data", "rerun": "0"}}, "suite_name": "tests/test_hw_29_postgres.py"}}}, "date": "December 02, 2024", "start_time": 1733169927.3275986, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "1", "fail": "3", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "4"}